@extends('layouts.admin')
@section('title','Administración')
@section('content')
<div class="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-8"><div><p class="text-violet text-xs uppercase tracking-[.18em] font-bold">Superadmin</p><h1 class="font-display text-3xl lg:text-4xl font-extrabold mt-2">Vista global</h1><p class="text-gray-500 mt-2">Actividad de todos los workspaces de Buy Overcloud.</p></div><a href="{{ route('clients') }}" class="bg-ink text-white rounded-xl px-5 py-3 text-sm font-semibold">Gestionar clientes →</a></div>
@php($cards=[['Clientes',$stats['clients'],'Workspaces privados'],['Números activos',$stats['numbers'],'WhatsApp Business'],['Mensajes hoy',$stats['outbound_today'],'Salientes en todos los clientes'],['Campañas activas',$stats['campaigns_active'],'En proceso']])
<div class="grid sm:grid-cols-2 xl:grid-cols-4 gap-5 mb-7">@foreach($cards as $i=>$card)<div class="bg-white rounded-[22px] border border-black/5 p-6 shadow-soft"><span class="w-10 h-10 rounded-xl bg-violet/10 text-violet grid place-items-center font-bold">{{ $i + 1 }}</span><p class="font-display text-3xl font-extrabold mt-5">{{ number_format($card[1]) }}</p><p class="font-semibold text-sm mt-1">{{ $card[0] }}</p><p class="text-xs text-gray-400 mt-1">{{ $card[2] }}</p></div>@endforeach</div>
<div class="grid xl:grid-cols-[.9fr_1.1fr] gap-6"><section class="bg-white rounded-[24px] border border-black/5 p-6"><div class="flex items-center justify-between mb-5"><div><h2 class="font-display font-bold text-xl">Clientes y conexiones</h2><p class="text-sm text-gray-400">Acceso, números y cupos actuales.</p></div><a href="{{ route('clients') }}" class="text-violet text-sm font-semibold">Gestionar</a></div><div class="space-y-3">@foreach($clients as $client)@php($limit=data_get($client->settings,'outbound_message_limit'))<div class="border rounded-2xl p-4"><div class="flex justify-between gap-3"><div><p class="font-semibold">{{ $client->name }}</p><p class="text-xs text-gray-400 mt-1">{{ $client->users->pluck('email')->join(', ') ?: 'Sin usuario' }}</p></div><span class="text-xs h-fit px-2 py-1 rounded-full {{ $client->status === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">{{ $client->status }}</span></div><div class="mt-3 text-xs text-gray-500 flex flex-wrap gap-x-4 gap-y-1"><span>{{ $client->whatsappConnections->where('status','connected')->count() }} número(s) conectado(s)</span>@if($limit)<span>Cupo: {{ $limit }} mensajes</span>@endif</div></div>@endforeach</div></section>
<section class="bg-white rounded-[24px] border border-black/5 p-6"><div class="mb-5"><h2 class="font-display font-bold text-xl">Últimos mensajes</h2><p class="text-sm text-gray-400">Entrantes y salientes de todos los clientes.</p></div><div class="divide-y">@forelse($messages as $message)@php($organization=$organizations->get($message->organization_id); $contact=$contacts->get($message->contact_id))<div class="py-4"><div class="flex justify-between gap-3"><div><p class="text-sm font-semibold">{{ $organization?->name ?? 'Workspace eliminado' }} <span class="font-normal text-gray-400">· {{ $contact?->nombre_display ?? 'Sin contacto' }}</span></p><p class="text-sm text-gray-600 mt-1 line-clamp-2 whitespace-pre-line">{{ $message->content }}</p></div><span class="text-[10px] h-fit px-2 py-1 rounded-full {{ $message->direction === 'out' ? 'bg-violet/10 text-violet' : 'bg-cyan-100 text-cyan-700' }}">{{ $message->direction === 'out' ? 'Enviado' : 'Recibido' }}</span></div><p class="text-[11px] text-gray-400 mt-2">{{ $message->created_at->format('d/m H:i') }} · {{ $message->status }}</p></div>@empty<div class="text-center py-12 text-gray-400">Aún no hay mensajes registrados.</div>@endforelse</div></section></div>
<section class="bg-white rounded-[24px] border border-black/5 p-6 mt-6"><div class="mb-5"><h2 class="font-display font-bold text-xl">Campañas recientes</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-left text-xs uppercase tracking-wider text-gray-400"><tr><th class="pb-3">Workspace</th><th class="pb-3">Campaña</th><th class="pb-3">Estado</th><th class="pb-3">Enviados</th><th class="pb-3">Fecha</th></tr></thead><tbody class="divide-y">@forelse($campaigns as $campaign)<tr><td class="py-3">{{ $organizations->get($campaign->organization_id)?->name ?? '—' }}</td><td class="py-3 font-medium">{{ $campaign->name }}</td><td class="py-3">{{ $campaign->status }}</td><td class="py-3">{{ $campaign->sent_count }}/{{ $campaign->total_contacts }}</td><td class="py-3 text-gray-400">{{ $campaign->created_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-gray-400">Aún no hay campañas.</td></tr>@endforelse</tbody></table></div></section>
@endsection
